### ISSUE TITLE
Unable to use network after stop b2g / start b2g

### ISSUE THREAD

**Issue by lissyx** [kaiostech/gecko-b2g#23]
Repro'd on device (sargo) and emulator-10-x86_64

STR:
 1. Boot, connect to network
 2. Load a page to check
 3. `adb shell stop b2g; adb shell start b2g`

Expected:
 I can see WiFi networks and connect to one

Actual:
 Scanning networks never returns anything, killing / restarting `netd` or `wpa_supplicant` does not help

Logcat after restart:
```
07-09 07:49:45.549  1657  1786 D APM_AudioPolicyManager: setVolumeCurveIndex: wrong index 3 min=0 max=0
07-09 07:49:45.549  1657  1786 E APM_AudioPolicyManager: setVolumeIndexForAttributes failed to set curve index for group 1 device 0x40000000
07-09 07:49:45.552  2179  2179 E gecko_sidl::common::uds_transport: Failed to connect to UDS socket /dev/socket/api-daemon : No such file or directory (os error 2)
07-09 07:49:45.552  2179  2179 E gecko_sidl::services::settings::service: Failed to connect to api-daemon socket
07-09 07:49:45.552  1657  1788 W AudioFlinger: no wake lock to update, system not ready yet
07-09 07:49:45.553  2179  2179 E gecko_sidl::common::uds_transport: Failed to connect to UDS socket /dev/socket/api-daemon : No such file or directory (os error 2)
07-09 07:49:45.553  2179  2179 E gecko_sidl::services::settings::service: Failed to connect to api-daemon socket
07-09 07:49:45.553  2179  2179 I Gecko   : -*- RadioInterface[0]: sendWorkerMessage: rilMessageType: getCurrentCalls: null
07-09 07:49:45.554  2179  2179 I Gecko   : -*- RadioInterface[0]: RILJ: [1] > RIL_REQUEST_GET_CURRENT_CALLS
07-09 07:49:45.554  2179  2179 I RilWorker: nsRilWorker: [1] > RIL_REQUEST_GET_CURRENT_CALLS
07-09 07:49:45.554  2179  2187 I RilWorker: processResponse, type= 0
07-09 07:49:45.554  2179  2187 I  nsRilResult: init nsRilResult for response.
07-09 07:49:45.554  2179  2187 I nsRilResponseResult: init nsRilResponseResult
07-09 07:49:45.554  2179  2187 I nsRilResponse: getCurrentCalls numCalls= 0
07-09 07:49:45.554  2179  2187 I  nsRilResponseResult: updateCurrentCalls
07-09 07:49:45.554  2179  2187 I RilWorker: nsRilWorker: [1] < getCurrentCalls
07-09 07:49:45.554  2179  2187 I RilWorker: RilResultDispatcher nsRilResponseResult
07-09 07:49:45.554  2179  2187 I RilWorker: ResponseResult.mRilMessageType done.
07-09 07:49:45.558  2179  2179 I Gecko   : console.log: "-*- NetworkService: " "Starting NetworkService." "\n"
07-09 07:49:45.558  2179  2179 I GeckoConsole: Content JS LOG: 
07-09 07:49:45.558  2179  2179 I NetworkUtils: Start Netd Service
07-09 07:49:45.558  2179  2179 I NetworkUtils: Dispatch Netd thread
07-09 07:49:45.559  2179  2217 I NetworkUtils: NetdInitRunnable enter
07-09 07:49:45.559  2179  2179 E gecko_sidl::common::uds_transport: Failed to connect to UDS socket /dev/socket/api-daemon : No such file or directory (os error 2)
07-09 07:49:45.559  2179  2179 E gecko_sidl::services::settings::service: Failed to connect to api-daemon socket
07-09 07:49:45.559  2179  2179 E GeckoConsole: [JavaScript Error: "NS_ERROR_XPC_GS_RETURNED_FAILURE: ServiceManager::GetService returned failure code:" {file: "resource://gre/modules/XPCOMUtils.jsm" line: 12}]
07-09 07:49:45.559  2179  2179 E GeckoConsole: XPCU_serviceLambda@resource://gre/modules/XPCOMUtils.jsm:12:108
07-09 07:49:45.559  2179  2179 E GeckoConsole: get@resource://gre/modules/XPCOMUtils.jsm:8:55
07-09 07:49:45.559  2179  2179 E GeckoConsole: getSettingValue@resource://gre/modules/TetheringService.jsm:12:4
07-09 07:49:45.559  2179  2179 E GeckoConsole: TetheringService@resource://gre/modules/TetheringService.jsm:5:93
07-09 07:49:45.559  2179  2179 I GeckoConsole: While creating services from category 'profile-after-change', could not create service for entry 'TetheringService', contract ID '@mozilla.org/tethering/service;1'
07-09 07:49:45.559  2179  2217 I NetworkUtils: Assigned gNetd/gDnsResolver
07-09 07:49:45.561  1710  1836 I netd    : registerUnsolicitedEventListener() <1.00ms>
07-09 07:49:45.561  2179  2217 I NetworkUtils: Registered NetdUnsolService Successful
07-09 07:49:45.561  2179  2217 I NetworkUtils: Request netd to create a network with netid 100
07-09 07:49:45.562  1710  1836 E Netd    : duplicate netId 100
07-09 07:49:45.562  1710  1836 I netd    : networkCreatePhysical(100, 0) -> ServiceSpecificException(17, "File exists") <0.07ms>
07-09 07:49:45.562  1710  1836 E res_cache: resolv_create_cache_for_net_locked: Cache is already created, netId: 100
07-09 07:49:45.562  1710  1836 I netd    : createNetworkCache(100) -> ServiceSpecificException(17, "File exists") <0.17ms>
07-09 07:49:45.562  2179  2217 I NetworkUtils: createNetwork physical failed, networkCache failed
07-09 07:49:45.563  1710  1836 D TcpSocketMonitor: resuming tcpinfo polling (interval=30000ms)
07-09 07:49:45.563  1710  1836 I netd    : networkDestroy(100) <0.10ms>
07-09 07:49:45.563  1710  1836 I netd    : destroyNetworkCache(100) <0.18ms>
07-09 07:49:45.563  2179  2217 I NetworkUtils: No command chain left in the queue. Done!
07-09 07:49:44.007  1938  1938 I chatty  : uid=0(root) /system/bin/sdcard identical 72 lines
07-09 07:49:45.007  1938  1938 E sdcard  : installd fs upgrade not yet complete; waiting...
07-09 07:49:45.570  1653  1653 I android.hardware.wifi@1.0-service: Legacy HAL stop complete callback received
07-09 07:49:45.571  1904  1904 I hostapd : wlan1: AP-STA-DISCONNECTED 02:00:00:00:00:00
07-09 07:49:45.572  2027  2027 D wpa_supplicant: nl80211: Ignored event (cmd=20) for foreign interface (ifindex 3 wdev 0x0)
07-09 07:49:45.572  2027  2027 D wpa_supplicant: nl80211: Drv Event 20 (NL80211_CMD_DEL_STATION) received for wlan0
07-09 07:49:45.572  2027  2027 D wpa_supplicant: nl80211: Delete station 02:00:00:00:01:00
07-09 07:49:45.572  2027  2027 D wpa_supplicant: nl80211: Ignored event (cmd=39) for foreign interface (ifindex 3 wdev 0x0)
07-09 07:49:45.572  2027  2027 D wpa_supplicant: nl80211: Drv Event 39 (NL80211_CMD_DEAUTHENTICATE) received for wlan0
07-09 07:49:45.572  2027  2027 D wpa_supplicant: nl80211: Deauthenticate event
07-09 07:49:45.572  2027  2027 D wpa_supplicant: wlan0: Event DEAUTH (11) received
07-09 07:49:45.572  2027  2027 D wpa_supplicant: wlan0: Deauthentication notification
07-09 07:49:45.572  2027  2027 D wpa_supplicant: wlan0:  * reason 3 (locally generated)
07-09 07:49:45.572  2027  2027 D wpa_supplicant: wlan0:  * address 02:00:00:00:01:00
07-09 07:49:45.572  2027  2027 D wpa_supplicant: Deauthentication frame IE(s) - hexdump(len=0): [NULL]
07-09 07:49:45.572  2027  2027 I wpa_supplicant: wlan0: CTRL-EVENT-DISCONNECTED bssid=02:00:00:00:01:00 reason=3 locally_generated=1
07-09 07:49:45.572  2027  2027 D wpa_supplicant: wlan0: Auto connect enabled: try to reconnect (wps=0/0 wpa_state=9)
07-09 07:49:45.572  2027  2027 D wpa_supplicant: wlan0: Setting scan request: 0.100000 sec
07-09 07:49:45.572  2027  2027 D wpa_supplicant: Added BSSID 02:00:00:00:01:00 into blacklist
07-09 07:49:45.572  2027  2027 D wpa_supplicant: wlan0: Blacklist count 1 --> request scan in 100 ms
07-09 07:49:45.572  2027  2027 D wpa_supplicant: wlan0: Ignore new scan request for 0.100000 sec since an earlier request is scheduled to trigger sooner
07-09 07:49:45.572  2027  2027 D wpa_supplicant: TDLS: Remove peers on disassociation
07-09 07:49:45.573  2027  2027 D wpa_supplicant: wlan0: WPA: Clear old PMK and PTK
07-09 07:49:45.573  2027  2027 D wpa_supplicant: Notifying disconnect reason to hidl control: -3
07-09 07:49:45.573  2027  2027 E wpa_supplicant: Failed to invoke HIDL iface callback
07-09 07:49:45.573  2027  2027 D wpa_supplicant: nl80211: Data frame filter flags=0x0
07-09 07:49:45.573  2027  2027 D wpa_supplicant: wlan0: State: COMPLETED -> DISCONNECTED
07-09 07:49:45.573  2027  2027 D wpa_supplicant: nl80211: Set wlan0 operstate 1->0 (DORMANT)
07-09 07:49:45.573  2027  2027 D wpa_supplicant: netlink: Operstate: ifindex=3 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
07-09 07:49:45.574  2179  2218 D WifiNative: command result: id=0, status=0
07-09 07:49:45.579  2179  2188 W Gonk    : Frame delay is 33333 us but decoding took 46433 us
07-09 07:49:45.579  2179  2188 I Gonk    : Decoded bootup/bootup_009.png: 240 x 320 frame with bgcolor? no (0, 0, 0; gray:0)
07-09 07:49:45.580  2179  2188 E gralloc_ranchu: gralloc_lock usage mismatch usage=0x1030 cb->usage=0x1a00
07-09 07:49:45.580  1648  1853 W EmuHWC2 : validate: layer 3 CompositionType 1, fallback
07-09 07:49:45.589  2046  2046 E dhcpcd  : wlan0: dhcp if_readrawpacket: Network is down
07-09 07:49:45.591  2179  2199 I NetdUnsolService: Iface linkstate wlan0 down
07-09 07:49:45.591  2179  2199 I NetdUnsolService: Route removed fe80::/64 dev wlan0
07-09 07:49:45.591  2179  2199 I NetdUnsolService: Route removed fec0::/64 dev wlan0
07-09 07:49:45.591  2179  2199 I NetdUnsolService: Route removed ::/0 via fe80::ff:fe00:100 dev wlan0
07-09 07:49:45.591  2179  2199 I NetdUnsolService: Address updated fec0::ff:fe00:0/64 wlan0 0 200
07-09 07:49:45.591  2179  2199 I NetdUnsolService: Address updated fe80::ff:fe00:0/64 wlan0 128 253
07-09 07:49:45.592  2027  2027 D wpa_supplicant: WMM AC: WMM AC is disabled
07-09 07:49:45.592  2027  2027 D wpa_supplicant: Notifying state change event to hidl control: 0
07-09 07:49:45.592  1653  1653 I android.hardware.wifi@1.0-service: Wifi HAL stopped
07-09 07:49:45.593  2027  2027 E wpa_supplicant: Failed to invoke HIDL iface callback
07-09 07:49:45.593  2027  2027 D wpa_supplicant: wlan0: Determining shared radio frequencies (max len 2)
07-09 07:49:45.593  2179  2187 D WifiHal : stop wifi: 0
07-09 07:49:45.593  2027  2027 D wpa_supplicant: wlan0: Shared frequencies (len=0): completed iteration
07-09 07:49:45.593  2027  2027 D wpa_supplicant: P2P: Add operating class 81
07-09 07:49:45.593  2027  2027 D wpa_supplicant: P2P: Channels - hexdump(len=11): 01 02 03 04 05 06 07 08 09 0a 0b
07-09 07:49:45.593  2027  2027 D wpa_supplicant: P2P: Update channel list
07-09 07:49:45.593  2027  2027 D wpa_supplicant: P2P: channels: 81:1,2,3,4,5,6,7,8,9,10,11
07-09 07:49:45.593  2027  2027 D wpa_supplicant: P2P: cli_channels:
07-09 07:49:45.593  2027  2027 D wpa_supplicant: Notifying bssid changed to hidl control
07-09 07:49:45.593  2027  2027 E wpa_supplicant: Failed to invoke HIDL iface callback
07-09 07:49:45.593  2027  2027 D wpa_supplicant: EAPOL: External notification - portEnabled=0
07-09 07:49:45.593  2027  2027 D wpa_supplicant: EAPOL: SUPP_PAE entering state DISCONNECTED
07-09 07:49:45.593  2027  2027 D wpa_supplicant: EAPOL: Supplicant port status: Unauthorized
07-09 07:49:45.593  2027  2027 D wpa_supplicant: nl80211: Skip set_supp_port(unauthorized) while not associated
07-09 07:49:45.593  2027  2027 D wpa_supplicant: EAPOL: SUPP_BE entering state INITIALIZE
07-09 07:49:45.593  2027  2027 D wpa_supplicant: EAPOL: External notification - portValid=0
07-09 07:49:45.593  2027  2027 D wpa_supplicant: RTM_NEWLINK: ifi_index=3 ifname=wlan0 operstate=2 linkmode=1 ifi_family=0 ifi_flags=0x1002 ()
07-09 07:49:45.593  2027  2027 D wpa_supplicant: nl80211: Interface down (wlan0/wlan0)
07-09 07:49:45.593  2027  2027 D wpa_supplicant: wlan0: Event INTERFACE_DISABLED (26) received
07-09 07:49:45.593  2027  2027 D wpa_supplicant: wlan0: Interface was disabled
07-09 07:49:45.593  2027  2027 D wpa_supplicant: nl80211: Data frame filter flags=0x0
07-09 07:49:45.593  2027  2027 D wpa_supplicant: wlan0: State: DISCONNECTED -> DISCONNECTED
07-09 07:49:45.594  2027  2027 D wpa_supplicant: nl80211: Set wlan0 operstate 0->0 (DORMANT)
07-09 07:49:45.594  2027  2027 D wpa_supplicant: netlink: Operstate: ifindex=3 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
07-09 07:49:45.594  2027  2027 D wpa_supplicant: EAPOL: External notification - portEnabled=0
07-09 07:49:45.594  2027  2027 D wpa_supplicant: EAPOL: External notification - portValid=0
07-09 07:49:45.594  2027  2027 D wpa_supplicant: wlan0: BSS: Remove id 0 BSSID 02:00:00:00:01:00 SSID 'AndroidWifi' due to wpa_bss_flush
07-09 07:49:45.594  2027  2027 D wpa_supplicant: wlan0: State: DISCONNECTED -> INTERFACE_DISABLED
07-09 07:49:45.594  2027  2027 D wpa_supplicant: Notifying state change event to hidl control: 1
07-09 07:49:45.594  2027  2027 E wpa_supplicant: Failed to invoke HIDL iface callback
07-09 07:49:45.594  2027  2027 D wpa_supplicant: wlan0: Determining shared radio frequencies (max len 2)
07-09 07:49:45.594  2027  2027 D wpa_supplicant: wlan0: Shared frequencies (len=0): completed iteration
07-09 07:49:45.594  2027  2027 D wpa_supplicant: P2P: Add operating class 81
07-09 07:49:45.594  2027  2027 D wpa_supplicant: P2P: Channels - hexdump(len=11): 01 02 03 04 05 06 07 08 09 0a 0b
07-09 07:49:45.594  2027  2027 D wpa_supplicant: P2P: Update channel list
07-09 07:49:45.594  2027  2027 D wpa_supplicant: P2P: channels: 81:1,2,3,4,5,6,7,8,9,10,11
07-09 07:49:45.594  2027  2027 D wpa_supplicant: P2P: cli_channels:
07-09 07:49:45.594  2027  2027 D wpa_supplicant: nl80211: Ignored event (cmd=48) for foreign interface (ifindex 3 wdev 0x0)
07-09 07:49:45.594  2027  2027 D wpa_supplicant: nl80211: Drv Event 48 (NL80211_CMD_DISCONNECT) received for wlan0
07-09 07:49:45.594  2027  2027 D wpa_supplicant: nl80211: Ignore disconnect event when using userspace SME
07-09 07:49:45.594  2027  2027 D wpa_supplicant: l2_packet_receive - recvfrom: Network is down
07-09 07:49:45.594  2027  2027 D wpa_supplicant: l2_packet_receive - recvfrom: Network is down
07-09 07:49:45.595  2179  2187 D WifiHal : WifiEventCallback.onStop()
07-09 07:49:45.613  2179  2179 I Gecko   : console.log: "-*- NetworkManager: " "Evaluating whether active network needs to be changed." "\n"
07-09 07:49:45.613  2179  2179 I GeckoConsole: Content JS LOG: 
07-09 07:49:45.614  2179  2217 I NetworkUtils: Interface rmnet0 (100) has been created.
07-09 07:49:45.625  2179  2188 W Gonk    : Frame delay is 33333 us but decoding took 45904 us
07-09 07:49:45.625  2179  2188 I Gonk    : Decoded bootup/bootup_010.png: 240 x 320 frame with bgcolor? no (0, 0, 0; gray:0)
07-09 07:49:45.625  2179  2188 E gralloc_ranchu: gralloc_lock usage mismatch usage=0x1030 cb->usage=0x1a00
07-09 07:49:45.626  1648  1853 W EmuHWC2 : validate: layer 3 CompositionType 1, fallback
07-09 07:49:45.669  2179  2188 W Gonk    : Frame delay is 33333 us but decoding took 44355 us
07-09 07:49:45.669  2179  2188 I Gonk    : Decoded bootup/bootup_011.png: 240 x 320 frame with bgcolor? no (0, 0, 0; gray:0)
07-09 07:49:45.670  2179  2188 E gralloc_ranchu: gralloc_lock usage mismatch usage=0x1030 cb->usage=0x1a00
07-09 07:49:45.670  1648  1853 W EmuHWC2 : validate: layer 3 CompositionType 1, fallback
07-09 07:49:45.672  2027  2027 D wpa_supplicant: wlan0: Skip scan - interface disabled
07-09 07:49:45.713  2179  2188 W Gonk    : Frame delay is 33333 us but decoding took 44240 us
07-09 07:49:45.713  2179  2188 I Gonk    : Decoded bootup/bootup_012.png: 240 x 320 frame with bgcolor? no (0, 0, 0; gray:0)
07-09 07:49:45.714  2179  2188 E gralloc_ranchu: gralloc_lock usage mismatch usage=0x1030 cb->usage=0x1a00
07-09 07:49:45.715  1648  1853 W EmuHWC2 : validate: layer 3 CompositionType 1, fallback
07-09 07:49:45.753  1648  1853 W EmuHWC2 : validate: layer 3 CompositionType 1, fallback
07-09 07:49:45.753  2179  2188 W Gonk    : Frame delay is 33333 us but decoding took 39747 us
07-09 07:49:45.753  2179  2188 I Gonk    : Decoded bootup/bootup_013.png: 240 x 320 frame with bgcolor? no (0, 0, 0; gray:0)
07-09 07:49:45.754  2179  2188 E gralloc_ranchu: gralloc_lock usage mismatch usage=0x1030 cb->usage=0x1a00
07-09 07:49:45.755  2179  2179 I Gecko   : -*- RadioInterface[0]: 0
07-09 07:49:45.755  2179  2179 I Gecko   : -*- RadioInterface[0]: message.rilMessageType:rilconnected
07-09 07:49:45.755  2179  2179 I Gecko   : -*- RadioInterface[0]: RILJ: [UNSL]< RIL_UNSOL_RIL_CONNECTED
07-09 07:49:45.755  2179  2179 I Gecko   : -*- RadioInterface[0]: RILJ: [2] > RIL_REQUEST_RADIO_POWER on = false
07-09 07:49:45.755  2179  2179 I RilWorker: nsRilWorker: [2] > RIL_REQUEST_RADIO_POWER on = 0
07-09 07:49:45.755  2179  2179 I Gecko   : -*- RadioInterface[0]: RILJ: [3] > RIL_REQUEST_SET_CELL_INFO_LIST_RATE rateInMillis = undefined
07-09 07:49:45.755  2179  2179 I RilWorker: nsRilWorker: [3] > RIL_REQUEST_SET_CELL_INFO_LIST_RATE rateInMillis = 0
07-09 07:49:45.756  2179  2187 I RilWorker: processResponse, type= 0
07-09 07:49:45.756  2179  2187 I  nsRilResult: init nsRilResult for response.
07-09 07:49:45.756  2179  2187 I nsRilResponseResult: init nsRilResponseResult
07-09 07:49:45.756  2179  2187 I RilWorker: nsRilWorker: [2] < setRadioEnabled
07-09 07:49:45.756  2179  2187 I RilWorker: RilResultDispatcher nsRilResponseResult
07-09 07:49:45.756  2179  2187 I RilWorker: ResponseResult.mRilMessageType done.
07-09 07:49:45.756  2179  2187 I RilWorker: processResponse, type= 0
07-09 07:49:45.756  2179  2187 I  nsRilResult: init nsRilResult for response.
07-09 07:49:45.756  2179  2187 I nsRilResponseResult: init nsRilResponseResult
07-09 07:49:45.756  2179  2187 I RilWorker: nsRilWorker: [3] < setCellInfoListRate
07-09 07:49:45.756  2179  2187 I RilWorker: RilResultDispatcher nsRilResponseResult
07-09 07:49:45.756  2179  2187 I RilWorker: ResponseResult.mRilMessageType done.
07-09 07:49:45.765  2179  2179 I Gecko   : -*- RadioInterface[0]: 0
07-09 07:49:45.765  2179  2179 I Gecko   : -*- RadioInterface[0]: message.rilMessageType:radiostatechange
07-09 07:49:45.765  2179  2179 I Gecko   : -*- RadioInterface[0]: RILJ: [UNSL]< RIL_UNSOL_RESPONSE_RADIO_STATE_CHANGED, radioStateChanged: 1
07-09 07:49:45.765  2179  2179 I Gecko   : -*- RadioInterface[0]: Radio state changed from '-1' to '1'
07-09 07:49:45.765  2179  2179 I Gecko   : -*- RadioInterface[0]: RILJ: [4] > RIL_REQUEST_DEVICE_IDENTITY
07-09 07:49:45.765  2179  2179 I RilWorker: nsRilWorker: [4] > RIL_REQUEST_DEVICE_IDENTITY
07-09 07:49:45.765  2179  2179 I Gecko   : -*- RadioInterface[0]: RILJ: [5] > RIL_REQUEST_GET_RADIO_CAPABILITY
07-09 07:49:45.765  2179  2179 I RilWorker: nsRilWorker: [5] > RIL_REQUEST_GET_RADIO_CAPABILITY
07-09 07:49:45.765  2179  2179 I Gecko   : -*- RadioInterfaceLayer: RadioControl: deactivating data calls...
07-09 07:49:45.766  2179  2187 I RilWorker: processResponse, type= 0
07-09 07:49:45.766  2179  2187 I  nsRilResult: init nsRilResult for response.
07-09 07:49:45.766  2179  2187 I nsRilResponseResult: init nsRilResponseResult
07-09 07:49:45.766  2179  2187 I  nsRilResponseResult: updateDeviceIdentity
07-09 07:49:45.766  2179  2187 I RilWorker: nsRilWorker: [4] < getDeviceIdentity
07-09 07:49:45.766  2179  2179 I Gecko   : -*- DataCallHandler[0]: deactivateAllDataCalls: aReason=1
07-09 07:49:45.766  2179  2187 I RilWorker: RilResultDispatcher nsRilResponseResult
07-09 07:49:45.766  2179  2187 I RilWorker: ResponseResult.mRilMessageType done.
07-09 07:49:45.766  2179  2187 I RilWorker: processResponse, type= 0
07-09 07:49:45.766  2179  2187 I  nsRilResult: init nsRilResult for response.
07-09 07:49:45.766  2179  2187 I nsRilResponseResult: init nsRilResponseResult
07-09 07:49:45.766  2179  2187 I  nsRadioCapability: init nsRadioCapability
07-09 07:49:45.766  2179  2187 I  nsRilResponseResult: updateRadioCapability
07-09 07:49:45.766  2179  2187 I RilWorker: nsRilWorker: [5] < getRadioCapability
07-09 07:49:45.766  2179  2187 I RilWorker: RilResultDispatcher nsRilResponseResult
07-09 07:49:45.766  2179  2187 I RilWorker: ResponseResult.mRilMessageType done.
07-09 07:49:45.799  1648  1853 W EmuHWC2 : validate: layer 3 CompositionType 1, fallback
07-09 07:49:45.800  2179  2188 W Gonk    : Frame delay is 33333 us but decoding took 46487 us
07-09 07:49:45.800  2179  2188 I Gonk    : Decoded bootup/bootup_014.png: 240 x 320 frame with bgcolor? no (0, 0, 0; gray:0)
07-09 07:49:45.801  2179  2188 E gralloc_ranchu: gralloc_lock usage mismatch usage=0x1030 cb->usage=0x1a00
07-09 07:49:45.836  2179  2179 I Gecko   : -*- RadioInterface[0]: Received message from worker handleRilResponse:{"rilMessageType":"getCurrentCalls","rilMessageToken":1,"errorMsg":0,"imei":"","imeisv":"","esn":"","meid":"","radioTech":-437918235,"basebandVersion":"","cardStatus":null,"voiceRegStatus":null,"dataRegStatus":null,"operator":null,"nwModeManual":true,"signalStrength":null,"smsc":"","causeCode":-437918235,"vendorCause":"","type":-437918235,"dcResponse":null,"imsi":"","iccIo":null,"n":-437918235,"m":-437918235,"enable":true,"serviceClass":-437918235,"provisioned":-437918235,"ttyMode":-437918235,"muteEnable":true,"remainingRetries":-437918235,"enhancedVoicePrivacy":true,"radioCapability":null,"sms":null,"CDMA_ALPHA_INFO_BUFFER_LENGTH":64,"CDMA_NUMBER_INFO_BUFFER_LENGTH":81,"MAX_RILDS":3,"MAX_SOCKET_NAME_LENGTH":6,"MAX_CLIENT_ID_LENGTH":2,"MAX_DEBUG_SOCKET_NAME_LENGTH":12,"MAX_QEMU_PIPE_NAME_LENGTH":11,"MAX_UUID_LENGTH":64,"CARD_MAX_APPS":8,"CDMA_MAX_NUMBER_OF_INFO_RECS":10,"SS_INFO_MAX":4,"NUM_SERVICE_CLASSES":7,"NUM_TX_POWER_LEVELS":5,"RADIO
07-09 07:49:45.836  2179  2179 I Gecko   : -*- RadioInterface[0]: RILJ: [1] < RIL_REQUEST_GET_CURRENT_CALLS
07-09 07:49:45.836  2179  2179 I Gecko   : -*- RadioInterface[0]: handleCurrentCalls []
07-09 07:49:45.836  2179  2179 I Gecko   : -*- RadioInterface[0]: sendWorkerMessage: rilMessageType: getCurrentCalls: null
07-09 07:49:45.836  2179  2179 I Gecko   : -*- RadioInterface[0]: RILJ: [6] > RIL_REQUEST_GET_CURRENT_CALLS
07-09 07:49:45.836  2179  2179 I RilWorker: nsRilWorker: [6] > RIL_REQUEST_GET_CURRENT_CALLS
07-09 07:49:45.837  1657  1786 W APM::AudioPolicyEngine/Base: setPhoneState() setting same state 0
07-09 07:49:45.837  2179  2187 I RilWorker: processResponse, type= 0
07-09 07:49:45.837  1657  1786 W APM_AudioPolicyManager: setPhoneState() invalid or same state 0
07-09 07:49:45.837  2179  2187 I  nsRilResult: init nsRilResult for response.
07-09 07:49:45.837  2179  2187 I nsRilResponseResult: init nsRilResponseResult
07-09 07:49:45.837  2179  2187 I nsRilResponse: getCurrentCalls numCalls= 0
07-09 07:49:45.837  2179  2187 I  nsRilResponseResult: updateCurrentCalls
07-09 07:49:45.837  2179  2187 I RilWorker: nsRilWorker: [6] < getCurrentCalls
07-09 07:49:45.837  2179  2187 I RilWorker: RilResultDispatcher nsRilResponseResult
07-09 07:49:45.837  2179  2187 I RilWorker: ResponseResult.mRilMessageType done.
07-09 07:49:45.847  2179  2179 I Gecko   : console.log: "-*- NetworkService: " "NetworkService received message from worker: {\"broadcast\":false,\"clatdAddress\":\"\",\"curExternalIfname\":\"\",\"curInternalIfname\":\"\",\"dns1\":0,\"dns1_str\":\"\",\"dns2\":0,\"dns2_str\":\"\",\"enable\":false,\"error\":true,\"flag\":\"down\",\"gateway\":0,\"gateway_str\":\"\",\"id\":0,\"ipAddr\":\"\",\"ipaddr\":0,\"ipaddr_str\":\"\",\"lease\":0,\"macAddr\":\"\",\"mask\":0,\"mask_str\":\"\",\"netId\":\"\",\"prefixLength\":0,\"reason\":\"\",\"reply\":\"\",\"result\":false,\"resultCode\":0,\"resultReason\":\"\",\"ret\":false,\"route\":\"\",\"server\":0,\"server_str\":\"\",\"success\":false,\"topic\":\"\",\"vendor_str\":\"\"}" "\n"
07-09 07:49:45.847  1648  1853 W EmuHWC2 : validate: layer 3 CompositionType 1, fallback
07-09 07:49:45.847  2179  2179 I GeckoConsole: Content JS LOG: 
07-09 07:49:45.847  2179  2179 I Gecko   : console.log: "-*- TetheringService: " "Create a default Network interface: rmnet0" "\n"
07-09 07:49:45.847  2179  2188 W Gonk    : Frame delay is 33333 us but decoding took 47647 us
07-09 07:49:45.847  2179  2188 I Gonk    : Decoded bootup/bootup_015.png: 240 x 320 frame with bgcolor? no (0, 0, 0; gray:0)
07-09 07:49:45.847  2179  2179 I GeckoConsole: Content JS LOG: 
07-09 07:49:45.848  2179  2179 I Gecko   : console.log: "-*- NetworkService: " "dequeue id: 0" "\n"
07-09 07:49:45.848  2179  2179 I GeckoConsole: Content JS LOG: 
07-09 07:49:45.848  2179  2179 I Gecko   : console.log: "-*- NetworkService: " "Id 0 is not on top of the queue" "\n"
07-09 07:49:45.848  2179  2179 I GeckoConsole: Content JS LOG: 
07-09 07:49:45.849  2179  2188 E gralloc_ranchu: gralloc_lock usage mismatch usage=0x1030 cb->usage=0x1a00
07-09 07:49:45.888  2179  2179 I Gecko   : console.log: "-*- NetworkService: " "NetworkService received message from worker: {\"broadcast\":true,\"clatdAddress\":\"\",\"curExternalIfname\":\"\",\"curInternalIfname\":\"\",\"dns1\":0,\"dns1_str\":\"\",\"dns2\":0,\"dns2_str\":\"\",\"enable\":false,\"error\":false,\"flag\":\"down\",\"gateway\":0,\"gateway_str\":\"\",\"id\":0,\"ipAddr\":\"\",\"ipaddr\":0,\"ipaddr_str\":\"\",\"lease\":0,\"macAddr\":\"\",\"mask\":0,\"mask_str\":\"\",\"netId\":\"\",\"prefixLength\":0,\"reason\":\"Route removed fe80::/64 dev wlan0\",\"reply\":\"\",\"result\":false,\"resultCode\":0,\"resultReason\":\"\",\"ret\":false,\"route\":\"\",\"server\":0,\"server_str\":\"\",\"success\":false,\"topic\":\"route-change\",\"vendor_str\":\"\"}" "\n"
07-09 07:49:45.888  2179  2179 I GeckoConsole: Content JS LOG: 
07-09 07:49:45.896  2179  2188 W Gonk    : Frame delay is 33333 us but decoding took 48745 us
07-09 07:49:45.896  2179  2188 I Gonk    : Decoded bootup/bootup_016.png: 240 x 320 frame with bgcolor? no (0, 0, 0; gray:0)
07-09 07:49:45.897  2179  2188 E gralloc_ranchu: gralloc_lock usage mismatch usage=0x1030 cb->usage=0x1a00
07-09 07:49:45.897  1648  1853 W EmuHWC2 : validate: layer 3 CompositionType 1, fallback
07-09 07:49:45.898  2179  2179 I Gecko   : console.log: "-*- NetworkService: " "NetworkService received message from worker: {\"broadcast\":true,\"clatdAddress\":\"\",\"curExternalIfname\":\"\",\"curInternalIfname\":\"\",\"dns1\":0,\"dns1_str\":\"\",\"dns2\":0,\"dns2_str\":\"\",\"enable\":false,\"error\":false,\"flag\":\"down\",\"gateway\":0,\"gateway_str\":\"\",\"id\":0,\"ipAddr\":\"\",\"ipaddr\":0,\"ipaddr_str\":\"\",\"lease\":0,\"macAddr\":\"\",\"mask\":0,\"mask_str\":\"\",\"netId\":\"\",\"prefixLength\":0,\"reason\":\"Route removed fec0::/64 dev wlan0\",\"reply\":\"\",\"result\":false,\"resultCode\":0,\"resultReason\":\"\",\"ret\":false,\"route\":\"\",\"server\":0,\"server_str\":\"\",\"success\":false,\"topic\":\"route-change\",\"vendor_str\":\"\"}" "\n"
07-09 07:49:45.898  1648  1853 W EmuHWC2 : validate: layer 3 CompositionType 1, fallback
07-09 07:49:45.898  2179  2179 I GeckoConsole: Content JS LOG: 
07-09 07:49:45.908  2179  2179 I Gecko   : console.log: "-*- NetworkService: " "NetworkService received message from worker: {\"broadcast\":true,\"clatdAddress\":\"\",\"curExternalIfname\":\"\",\"curInternalIfname\":\"\",\"dns1\":0,\"dns1_str\":\"\",\"dns2\":0,\"dns2_str\":\"\",\"enable\":false,\"error\":false,\"flag\":\"down\",\"gateway\":0,\"gateway_str\":\"\",\"id\":0,\"ipAddr\":\"\",\"ipaddr\":0,\"ipaddr_str\":\"\",\"lease\":0,\"macAddr\":\"\",\"mask\":0,\"mask_str\":\"\",\"netId\":\"\",\"prefixLength\":0,\"reason\":\"Route removed ::/0 via fe80::ff:fe00:100 dev wlan0\",\"reply\":\"\",\"result\":false,\"resultCode\":0,\"resultReason\":\"\",\"ret\":false,\"route\":\"\",\"server\":0,\"server_str\":\"\",\"success\":false,\"topic\":\"route-change\",\"vendor_str\":\"\"}" "\n"
07-09 07:49:45.908  2179  2179 I GeckoConsole: Content JS LOG: 
07-09 07:49:45.908  2179  2179 I Gecko   : -*- WifiWorker component: Interface null updateConfig: removed {"gateway":"fe80::ff:fe00:100"}
07-09 07:49:45.918  2179  2179 I Gecko   : console.log: "-*- NetworkService: " "NetworkService received message from worker: {\"broadcast\":true,\"clatdAddress\":\"\",\"curExternalIfname\":\"\",\"curInternalIfname\":\"\",\"dns1\":0,\"dns1_str\":\"\",\"dns2\":0,\"dns2_str\":\"\",\"enable\":false,\"error\":false,\"flag\":\"down\",\"gateway\":0,\"gateway_str\":\"\",\"id\":0,\"ipAddr\":\"\",\"ipaddr\":0,\"ipaddr_str\":\"\",\"lease\":0,\"macAddr\":\"\",\"mask\":0,\"mask_str\":\"\",\"netId\":\"\",\"prefixLength\":0,\"reason\":\"Address updated fec0::ff:fe00:0/64 wlan0 0 200\",\"reply\":\"\",\"result\":false,\"resultCode\":0,\"resultReason\":\"\",\"ret\":false,\"route\":\"\",\"server\":0,\"server_str\":\"\",\"success\":false,\"topic\":\"interface-address-change\",\"vendor_str\":\"\"}" "\n"
07-09 07:49:45.918  2179  2179 I GeckoConsole: Content JS LOG: 
07-09 07:49:45.918  2179  2179 I Gecko   : -*- WifiWorker component: Interface null updateConfig: updated {"ip":"fec0::ff:fe00:0","prefixLengths":"64"}
07-09 07:49:45.928  2179  2179 I Gecko   : console.log: "-*- NetworkService: " "NetworkService received message from worker: {\"broadcast\":true,\"clatdAddress\":\"\",\"curExternalIfname\":\"\",\"curInternalIfname\":\"\",\"dns1\":0,\"dns1_str\":\"\",\"dns2\":0,\"dns2_str\":\"\",\"enable\":false,\"error\":false,\"flag\":\"down\",\"gateway\":0,\"gateway_str\":\"\",\"id\":0,\"ipAddr\":\"\",\"ipaddr\":0,\"ipaddr_str\":\"\",\"lease\":0,\"macAddr\":\"\",\"mask\":0,\"mask_str\":\"\",\"netId\":\"\",\"prefixLength\":0,\"reason\":\"Address updated fe80::ff:fe00:0/64 wlan0 128 253\",\"reply\":\"\",\"result\":false,\"resultCode\":0,\"resultReason\":\"\",\"ret\":false,\"route\":\"\",\"server\":0,\"server_str\":\"\",\"success\":false,\"topic\":\"interface-address-change\",\"vendor_str\":\"\"}" "\n"
07-09 07:49:45.928  2179  2179 I GeckoConsole: Content JS LOG: 
07-09 07:49:45.928  2179  2179 I Gecko   : -*- WifiWorker component: Interface null updateConfig: updated {"ip":"fe80::ff:fe00:0","prefixLengths":"64"}
07-09 07:49:45.929  2179  2188 I Gonk    : Decoded bootup/bootup_017.png: 240 x 320 frame with bgcolor? no (0, 0, 0; gray:0)
07-09 07:49:45.931  2179  2188 E gralloc_ranchu: gralloc_lock usage mismatch usage=0x1030 cb->usage=0x1a00
07-09 07:49:45.943  1648  1853 W EmuHWC2 : validate: layer 3 CompositionType 1, fallback
07-09 07:49:45.964  2179  2188 E gralloc_ranchu: gralloc_lock usage mismatch usage=0x1030 cb->usage=0x1a00
07-09 07:49:45.996  1648  1853 W EmuHWC2 : validate: layer 3 CompositionType 1, fallback
07-09 07:49:45.997  2179  2188 W Gonk    : Frame delay is 33333 us but decoding took 33776 us
07-09 07:49:45.997  2179  2188 I Gonk    : Decoded bootup/bootup_019.png: 240 x 320 frame with bgcolor? no (0, 0, 0; gray:0)
07-09 07:49:45.999  2179  2188 E gralloc_ranchu: gralloc_lock usage mismatch usage=0x1030 cb->usage=0x1a00
07-09 07:49:46.007  1938  1938 E cutils  : Failed to read /data/.layout_version: No such file or directory
07-09 07:49:46.007  1938  1938 E sdcard  : installd fs upgrade not yet complete; waiting...
07-09 07:49:46.008  2179  2179 I Gecko   : console.log: "-*- NetworkService: " "NetworkService received message from worker: {\"broadcast\":false,\"clatdAddress\":\"\",\"curExternalIfname\":\"\",\"curInternalIfname\":\"\",\"dns1\":0,\"dns1_str\":\"\",\"dns2\":0,\"dns2_str\":\"\",\"enable\":false,\"error\":false,\"flag\":\"down\",\"gateway\":0,\"gateway_str\":\"\",\"id\":1,\"ipAddr\":\"\",\"ipaddr\":0,\"ipaddr_str\":\"\",\"lease\":0,\"macAddr\":\"\",\"mask\":0,\"mask_str\":\"\",\"netId\":\"\",\"prefixLength\":0,\"reason\":\"\",\"reply\":\"\",\"result\":false,\"resultCode\":0,\"resultReason\":\"\",\"ret\":false,\"route\":\"\",\"server\":0,\"server_str\":\"\",\"success\":false,\"topic\":\"\",\"vendor_str\":\"\"}" "\n"
07-09 07:49:46.008  2179  2179 I GeckoConsole: Content JS LOG: 
07-09 07:49:46.009  2179  2179 I Gecko   : console.log: "-*- TetheringService: " "Create a default Network interface: rmnet0" "\n"
07-09 07:49:46.009  2179  2179 I GeckoConsole: Content JS LOG: 
07-09 07:49:46.009  2179  2179 I Gecko   : console.log: "-*- NetworkService: " "dequeue id: 1" "\n"
07-09 07:49:46.009  2179  2179 I GeckoConsole: Content JS LOG: 
07-09 07:49:46.009  2179  2179 I Gecko   : console.log: "-*- NetworkService: " "Id 1 is not on top of the queue" "\n"
07-09 07:49:46.010  2179  2179 I GeckoConsole: Content JS LOG: 
07-09 07:49:46.044  2179  2188 W Gonk    : Frame delay is 33333 us but decoding took 47195 us
07-09 07:49:46.044  2179  2188 I Gonk    : Decoded bootup/bootup_020.png: 240 x 320 frame with bgcolor? no (0, 0, 0; gray:0)
07-09 07:49:46.045  1648  1853 W EmuHWC2 : validate: layer 3 CompositionType 1, fallback
07-09 07:49:46.048  2179  2188 E gralloc_ranchu: gralloc_lock usage mismatch usage=0x1030 cb->usage=0x1a00
07-09 07:49:46.090  2179  2188 W Gonk    : Frame delay is 33333 us but decoding took 46164 us
07-09 07:49:46.090  2179  2188 I Gonk    : Decoded bootup/bootup_021.png: 240 x 320 frame with bgcolor? no (0, 0, 0; gray:0)
07-09 07:49:46.092  1648  1853 W EmuHWC2 : validate: layer 3 CompositionType 1, fallback
07-09 07:49:46.094  2179  2188 E gralloc_ranchu: gralloc_lock usage mismatch usage=0x1030 cb->usage=0x1a00
07-09 07:49:46.134  1648  1853 W EmuHWC2 : validate: layer 3 CompositionType 1, fallback
07-09 07:49:46.134  2179  2188 W Gonk    : Frame delay is 33333 us but decoding took 43857 us
07-09 07:49:46.134  2179  2188 I Gonk    : Decoded bootup/bootup_022.png: 240 x 320 frame with bgcolor? no (0, 0, 0; gray:0)
07-09 07:49:46.137  2179  2188 E gralloc_ranchu: gralloc_lock usage mismatch usage=0x1030 cb->usage=0x1a00
07-09 07:49:46.139  2179  2179 I Gecko   : -*- RadioInterface[0]: Received message from worker handleRilResponse:{"rilMessageType":"setRadioEnabled","rilMessageToken":2,"errorMsg":0,"imei":"","imeisv":"","esn":"","meid":"","radioTech":-437918235,"basebandVersion":"","cardStatus":null,"voiceRegStatus":null,"dataRegStatus":null,"operator":null,"nwModeManual":true,"signalStrength":null,"smsc":"","causeCode":-437918235,"vendorCause":"","type":-437918235,"dcResponse":null,"imsi":"","iccIo":null,"n":-437918235,"m":-437918235,"enable":true,"serviceClass":-437918235,"provisioned":-437918235,"ttyMode":-437918235,"muteEnable":true,"remainingRetries":-437918235,"enhancedVoicePrivacy":true,"radioCapability":null,"sms":null,"CDMA_ALPHA_INFO_BUFFER_LENGTH":64,"CDMA_NUMBER_INFO_BUFFER_LENGTH":81,"MAX_RILDS":3,"MAX_SOCKET_NAME_LENGTH":6,"MAX_CLIENT_ID_LENGTH":2,"MAX_DEBUG_SOCKET_NAME_LENGTH":12,"MAX_QEMU_PIPE_NAME_LENGTH":11,"MAX_UUID_LENGTH":64,"CARD_MAX_APPS":8,"CDMA_MAX_NUMBER_OF_INFO_RECS":10,"SS_INFO_MAX":4,"NUM_SERVICE_CLASSES":7,"NUM_TX_POWER_LEVELS":5,"RADIO
07-09 07:49:46.139  2179  2179 I Gecko   : -*- RadioInterface[0]: RILJ: [2] < RIL_REQUEST_RADIO_POWER
07-09 07:49:46.139  2179  2179 I Gecko   : -*- RadioInterface[0]: 0
07-09 07:49:46.150  2179  2179 I Gecko   : -*- RadioInterface[0]: Received message from worker handleRilResponse:{"rilMessageType":"setCellInfoListRate","rilMessageToken":3,"errorMsg":0,"imei":"","imeisv":"","esn":"","meid":"","radioTech":0,"basebandVersion":"","cardStatus":null,"voiceRegStatus":null,"dataRegStatus":null,"operator":null,"nwModeManual":false,"signalStrength":null,"smsc":"","causeCode":0,"vendorCause":"","type":0,"dcResponse":null,"imsi":"","iccIo":null,"n":0,"m":0,"enable":false,"serviceClass":0,"provisioned":0,"ttyMode":0,"muteEnable":false,"remainingRetries":0,"enhancedVoicePrivacy":false,"radioCapability":null,"sms":null,"CDMA_ALPHA_INFO_BUFFER_LENGTH":64,"CDMA_NUMBER_INFO_BUFFER_LENGTH":81,"MAX_RILDS":3,"MAX_SOCKET_NAME_LENGTH":6,"MAX_CLIENT_ID_LENGTH":2,"MAX_DEBUG_SOCKET_NAME_LENGTH":12,"MAX_QEMU_PIPE_NAME_LENGTH":11,"MAX_UUID_LENGTH":64,"CARD_MAX_APPS":8,"CDMA_MAX_NUMBER_OF_INFO_RECS":10,"SS_INFO_MAX":4,"NUM_SERVICE_CLASSES":7,"NUM_TX_POWER_LEVELS":5,"RADIO_ERROR_NONE":0,"RADIO_ERROR_NOT_AVAILABLE":1,"RADIO_ERROR_GENERIC_FAILURE
07-09 07:49:46.150  2179  2179 I Gecko   : -*- RadioInterface[0]: RILJ: [3] < RIL_REQUEST_SET_CELL_INFO_LIST_RATE
07-09 07:49:46.150  2179  2179 I Gecko   : -*- RadioInterface[0]: 0
07-09 07:49:46.161  2179  2179 I Gecko   : -*- RadioInterface[0]: Received message from worker handleRilResponse:{"rilMessageType":"getDeviceIdentity","rilMessageToken":4,"errorMsg":0,"imei":"358240051111110","imeisv":"----","esn":"77777777","meid":"","radioTech":0,"basebandVersion":"","cardStatus":null,"voiceRegStatus":null,"dataRegStatus":null,"operator":null,"nwModeManual":false,"signalStrength":null,"smsc":"","causeCode":0,"vendorCause":"","type":0,"dcResponse":null,"imsi":"","iccIo":null,"n":0,"m":0,"enable":false,"serviceClass":0,"provisioned":0,"ttyMode":0,"muteEnable":false,"remainingRetries":0,"enhancedVoicePrivacy":false,"radioCapability":null,"sms":null,"CDMA_ALPHA_INFO_BUFFER_LENGTH":64,"CDMA_NUMBER_INFO_BUFFER_LENGTH":81,"MAX_RILDS":3,"MAX_SOCKET_NAME_LENGTH":6,"MAX_CLIENT_ID_LENGTH":2,"MAX_DEBUG_SOCKET_NAME_LENGTH":12,"MAX_QEMU_PIPE_NAME_LENGTH":11,"MAX_UUID_LENGTH":64,"CARD_MAX_APPS":8,"CDMA_MAX_NUMBER_OF_INFO_RECS":10,"SS_INFO_MAX":4,"NUM_SERVICE_CLASSES":7,"NUM_TX_POWER_LEVELS":5,"RADIO_ERROR_NONE":0,"RADIO_ERROR_NOT_AVAILABLE":1,"RA
07-09 07:49:46.161  2179  2179 I Gecko   : -*- RadioInterface[0]: RILJ: [4] < RIL_REQUEST_DEVICE_IDENTITY imei = 358240051111110 , imeisv = ---- ,esn = 77777777 , meid = 
07-09 07:49:46.161  2179  2179 I Gecko   : -*- RadioInterface[0]: handleDeviceIdentity imei=358240051111110, imeisv=---- ,esn =77777777 , meid=
07-09 07:49:46.162  2179  2179 I Gecko   : -*- RadioInterface[0]: 0
07-09 07:49:46.172  2179  2179 I Gecko   : -*- RadioInterface[0]: Received message from worker handleRilResponse:{"rilMessageType":"getRadioCapability","rilMessageToken":5,"errorMsg":0,"imei":"","imeisv":"","esn":"","meid":"","radioTech":0,"basebandVersion":"","cardStatus":null,"voiceRegStatus":null,"dataRegStatus":null,"operator":null,"nwModeManual":false,"signalStrength":null,"smsc":"","causeCode":0,"vendorCause":"","type":0,"dcResponse":null,"imsi":"","iccIo":null,"n":0,"m":0,"enable":false,"serviceClass":0,"provisioned":0,"ttyMode":0,"muteEnable":false,"remainingRetries":0,"enhancedVoicePrivacy":false,"radioCapability":{"session":0,"phase":0,"raf":16384,"logicalModemUuid":"","status":1},"sms":null,"CDMA_ALPHA_INFO_BUFFER_LENGTH":64,"CDMA_NUMBER_INFO_BUFFER_LENGTH":81,"MAX_RILDS":3,"MAX_SOCKET_NAME_LENGTH":6,"MAX_CLIENT_ID_LENGTH":2,"MAX_DEBUG_SOCKET_NAME_LENGTH":12,"MAX_QEMU_PIPE_NAME_LENGTH":11,"MAX_UUID_LENGTH":64,"CARD_MAX_APPS":8,"CDMA_MAX_NUMBER_OF_INFO_RECS":10,"SS_INFO_MAX":4,"NUM_SERVICE_CLASSES":7,"NUM_TX_POWER_LEVELS":5,"RADIO_ERROR_NON
07-09 07:49:46.172  2179  2179 I Gecko   : -*- RadioInterface[0]: RILJ: [5] < RIL_REQUEST_GET_RADIO_CAPABILITY
07-09 07:49:46.172  2179  2179 I Gecko   : -*- RadioInterface[0]: handleRadioCapability session=0, phase=0, raf=16384, logicalModemUuid=, status=1
07-09 07:49:46.172  2179  2179 I Gecko   : -*- RadioInterface[0]: 0
07-09 07:49:46.178  2179  2188 W Gonk    : Frame delay is 33333 us but decoding took 44177 us
07-09 07:49:46.179  2179  2188 I Gonk    : Decoded bootup/bootup_023.png: 240 x 320 frame with bgcolor? no (0, 0, 0; gray:0)
07-09 07:49:46.179  1648  1853 W EmuHWC2 : validate: layer 3 CompositionType 1, fallback
07-09 07:49:46.181  2179  2188 E gralloc_ranchu: gralloc_lock usage mismatch usage=0x1030 cb->usage=0x1a00
07-09 07:49:46.192  2179  2179 I Gecko   : -*- RadioInterface[0]: Received message from worker handleRilResponse:{"rilMessageType":"getCurrentCalls","rilMessageToken":6,"errorMsg":0,"imei":"","imeisv":"","esn":"","meid":"","radioTech":0,"basebandVersion":"","cardStatus":null,"voiceRegStatus":null,"dataRegStatus":null,"operator":null,"nwModeManual":false,"signalStrength":null,"smsc":"","causeCode":0,"vendorCause":"","type":0,"dcResponse":null,"imsi":"","iccIo":null,"n":0,"m":0,"enable":false,"serviceClass":0,"provisioned":0,"ttyMode":0,"muteEnable":false,"remainingRetries":0,"enhancedVoicePrivacy":false,"radioCapability":null,"sms":null,"CDMA_ALPHA_INFO_BUFFER_LENGTH":64,"CDMA_NUMBER_INFO_BUFFER_LENGTH":81,"MAX_RILDS":3,"MAX_SOCKET_NAME_LENGTH":6,"MAX_CLIENT_ID_LENGTH":2,"MAX_DEBUG_SOCKET_NAME_LENGTH":12,"MAX_QEMU_PIPE_NAME_LENGTH":11,"MAX_UUID_LENGTH":64,"CARD_MAX_APPS":8,"CDMA_MAX_NUMBER_OF_INFO_RECS":10,"SS_INFO_MAX":4,"NUM_SERVICE_CLASSES":7,"NUM_TX_POWER_LEVELS":5,"RADIO_ERROR_NONE":0,"RADIO_ERROR_NOT_AVAILABLE":1,"RADIO_ERROR_GENERIC_FAILURE":2,
07-09 07:49:46.192  2179  2179 I Gecko   : -*- RadioInterface[0]: RILJ: [6] < RIL_REQUEST_GET_CURRENT_CALLS
07-09 07:49:46.192  2179  2179 I Gecko   : -*- RadioInterface[0]: handleCurrentCalls []
07-09 07:49:46.222  1648  1853 W EmuHWC2 : validate: layer 3 CompositionType 1, fallback
07-09 07:49:46.222  2179  2188 W Gonk    : Frame delay is 33333 us but decoding took 43207 us
07-09 07:49:46.222  2179  2188 I Gonk    : Decoded bootup/bootup_024.png: 240 x 320 frame with bgcolor? no (0, 0, 0; gray:0)
07-09 07:49:46.223  2179  2188 E gralloc_ranchu: gralloc_lock usage mismatch usage=0x1030 cb->usage=0x1a00
07-09 07:49:46.264  2179  2188 W Gonk    : Frame delay is 33333 us but decoding took 42311 us
07-09 07:49:46.264  2179  2188 I Gonk    : Decoded bootup/bootup_025.png: 240 x 320 frame with bgcolor? no (0, 0, 0; gray:0)
07-09 07:49:46.265  1647  1672 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 770048
07-09 07:49:46.266  1648  1853 W EmuHWC2 : validate: layer 3 CompositionType 1, fallback
07-09 07:49:46.355  2179  2188 E gralloc_ranchu: gralloc_lock usage mismatch usage=0x1030 cb->usage=0x1a00
07-09 07:49:46.356  2179  2188 W Gonk    : Frame delay is 33333 us but decoding took 92163 us
07-09 07:49:46.356  2179  2188 I Gonk    : Decoded bootup/bootup_026.png: 240 x 320 frame with bgcolor? no (0, 0, 0; gray:0)
07-09 07:49:46.358  2179  2188 E gralloc_ranchu: gralloc_lock usage mismatch usage=0x1030 cb->usage=0x1a00
07-09 07:49:46.358  1648  1853 W EmuHWC2 : validate: layer 3 CompositionType 1, fallback
07-09 07:49:46.359  1648  1853 W EmuHWC2 : validate: layer 3 CompositionType 1, fallback
07-09 07:49:46.390  2179  2188 I Gonk    : Decoded bootup/bootup_027.png: 240 x 320 frame with bgcolor? no (0, 0, 0; gray:0)
07-09 07:49:46.391  2179  2188 E gralloc_ranchu: gralloc_lock usage mismatch usage=0x1030 cb->usage=0x1a00
07-09 07:49:46.403  1648  1853 W EmuHWC2 : validate: layer 3 CompositionType 1, fallback
07-09 07:49:46.426  2179  2188 I Gonk    : Decoded bootup/bootup_028.png: 240 x 320 frame with bgcolor? no (0, 0, 0; gray:0)
07-09 07:49:46.427  2179  2188 E gralloc_ranchu: gralloc_lock usage mismatch usage=0x1030 cb->usage=0x1a00
07-09 07:49:46.450  1648  1853 W EmuHWC2 : validate: layer 3 CompositionType 1, fallback
07-09 07:49:46.459  2179  2188 I Gonk    : Decoded bootup/bootup_029.png: 240 x 320 frame with bgcolor? no (0, 0, 0; gray:0)
07-09 07:49:46.461  2179  2188 E gralloc_ranchu: gralloc_lock usage mismatch usage=0x1030 cb->usage=0x1a00
07-09 07:49:46.450  2179  2179 I MainThread: type=1400 audit(0.0:400): avc: denied { wake_alarm } for capability=35 scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=capability2 permissive=1
07-09 07:49:46.466  2179  2179 I Gecko   : -*- DownloadService.jsm : init
07-09 07:49:46.470  2179  2179 I Gecko   : LocalDomains: scan
07-09 07:49:46.470  2179  2179 I Gecko   : LocalDomains: scanning /system/b2g/webapps
07-09 07:49:46.479  2179  2209 D libEGL  : Emulator has host GPU support, qemu.gles is set to 1.
07-09 07:49:46.480  2179  2209 D vndksupport: Loading /vendor/lib64/egl/libEGL_emulation.so from current namespace instead of sphal namespace.
07-09 07:49:46.480  2179  2209 D libEGL  : loaded /vendor/lib64/egl/libEGL_emulation.so
07-09 07:49:46.481  2179  2209 D vndksupport: Loading /vendor/lib64/egl/libGLESv1_CM_emulation.so from current namespace instead of sphal namespace.
07-09 07:49:46.481  2179  2209 D libEGL  : loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
07-09 07:49:46.482  2179  2209 D vndksupport: Loading /vendor/lib64/egl/libGLESv2_emulation.so from current namespace instead of sphal namespace.
07-09 07:49:46.482  2179  2209 D libEGL  : loaded /vendor/lib64/egl/libGLESv2_emulation.so
```

**Comment by fabricedesre** [comment]
The root cause has been identified and a fix is in progress

**Comment by lissyx** [comment]
@fabricedesre I've been told this was fixed, I have not yet been able to verify myself, do you know what commit fixed?

**Comment by brendandahl** [comment]
It seems the behavior has changed, but it's still broken. After stop/start, I can now see the android wifi network when I scan, but after I connect and try to go to a page I see `Network Connection Error: netOffline`

**Comment by fabricedesre** [comment]
https://github.com/kaiostech/gecko-b2g/commit/7cc7bafecb6f6eeb8cceb9b735ebaf56d62e2a33 should fix it until a more proper fix is implemented.

**Comment by brendandahl** [comment]
Working for me. Thanks!

**Comment by fabricedesre** [comment]
\o/
